### ISSUE TITLE
Add-FluentMigration

### ISSUE THREAD

**Issue by llotall** [ritterim/fluentmigrator-generator#11]
I use **.NET Core 2.1**
I know that this version of fluentmigrator-generator not complicated with this .net version.
But when i try add new migration, migration added but in console output i have exception:

```
PM> Add-FluentMigration TestMigration

Object               : Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAVSProjectItem
Document             : 
FileCount            : 1
Properties           : {LocalPath, Author, FullPath, CopyToOutputDirectory...}
FileCodeModel        : System.__ComObject
ProjectItems         : {}
Kind                 : {6BB5F8EE-4483-11D3-8BCF-00C04F8EC28C}
DTE                  : System.__ComObject
Collection           : {20181123202643_TestMigration.cs, AddCityTable.cs}
ExtenderNames        : {}
ConfigurationManager : System.__ComObject
ContainingProject    : Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProject
Saved                : True
ExtenderCATID        : {610D4615-D0D5-11D2-8599-006097C68E81}
SubProject           : 
IsDirty              : False
Name                 : 20181123202643_TestMigration.cs

Cannot find an overload for "Save" and the argument count: "0".
At C:\Users\llotall\.nuget\packages\fluentmigrator.generator\1.0.4\tools\FluentMigrator.psm1:39 char:5
+     $project.Save()
+     ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest

```
Please can you fix it.

**Comment by khalidabuhakmeh** [comment]
This version probably won't be ported to use .net core, in favor of a DOTNET global tool.

**Comment by llotall** [comment]
> This version probably won't be ported to use .net core, in favor of a DOTNET global tool.

Can you get me example?
What do you mean about .Net global tool?
Now i use Dapper and what alternative do i have for use add-migration from console package?

**Comment by Mikado68** [comment]
Hi all, I created a PR to fix that. 

Cheers
Julien

**Comment by ademchenko** [comment]
Hello, I see that the fix is merged https://github.com/ritterim/fluentmigrator-generator/pull/13 , but the package is not redeployed to NuGet, can you do that, please?

**Comment by mk148a** [comment]
That issue still in v.1.0.5

Here its my result:
PM> Add-FluentMigration InitialMigration


Object               : Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAVSProjectItem
Document             : 
FileCount            : 1
Properties           : {LocalPath, Author, FullPath, CopyToOutputDirectory...}
FileCodeModel        : System.__ComObject
ProjectItems         : {}
Kind                 : {6BB5F8EE-4483-11D3-8BCF-00C04F8EC28C}
DTE                  : System.__ComObject
Collection           : {Installation, UpgradeTo440, UpgradeTo450, 20230522165759_InitialMigration.cs...}
ExtenderNames        : {}
ConfigurationManager : System.__ComObject
ContainingProject    : Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProject
Saved                : True
ExtenderCATID        : {610D4615-D0D5-11D2-8599-006097C68E81}
SubProject           : 
IsDirty              : False
Name                 : 20230522165759_InitialMigration.cs

Cannot find an overload for "Save" and the argument count: "0".
At C:\Users\Murat\.nuget\packages\fluentmigrator.generator\1.0.5\tools\FluentMigrator.psm1:58 char:5
+     $project.Save()
+     ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest
